### ISSUE TITLE
Fuzzer additional work

### ISSUE THREAD

**Issue by pront** [vectordotdev/vrl#464]
```[tasklist]
### Tasks
- [ ] Fix [bugs](https://github.com/vectordotdev/vrl/issues?q=is%3Aopen+is%3Aissue+label%3Afuzz) discovered by the fuzzer
- [ ] Add more seeds/inputs.
- [ ] Currently will provide the input that caused a failure. We can make the fuzzer output a nicer report by re-running the failed program.
- [ ] Add a Github workflow that runs the fuzzer X times/week for Y hours/run.
```

The above list is not exhaustive but a good starting point.
